### ISSUE TITLE
Should this repo be archived?

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/CSS-Parser-API#13]
I'm a bit confused about this repository VS what's published over on the Houdini side of things? Or is this the canonical repository for this particular Houdini draft?

**Comment by gregwhitworth** [comment]
I would say for the time being it should be. @tabatkins let me know if you disagree.

**Comment by marcoscaceres** [comment]
@tabatkins friendly ping. Quick yes/no response needed.

**Comment by marcoscaceres** [comment]
Seems @tabatkins would like to keep this going, even if slowly.  https://github.com/WICG/admin/pull/116#issuecomment-638314739
