### ISSUE TITLE
https://wicg.github.io/css-parser-api/ needs to be redeployed

### ISSUE THREAD

**Issue by foolip** [WICG/CSS-Parser-API#18]
The changes in https://github.com/WICG/css-parser-api/pull/17 aren't reflected in https://wicg.github.io/css-parser-api/ and it looks like it's because there is no `gh-pages` branch, and the `index.html` in the `master` branch hasn't been updated.

@tabatkins would you be able to update this?

**Comment by tabatkins** [comment]
Done

**Comment by foolip** [comment]
Thanks Tab!
