### ISSUE TITLE
Should we have a the types that overlap with TypedOM reuse CSSStyleValue

### ISSUE THREAD

**Issue by gregwhitworth** [WICG/CSS-Parser-API#9]
In the current specification UD there is this issue: 

> Some of the CSSParserValue subtypes correspond closely to Typed OM types; in particular, {{CSSParserIdent}} and {{CSSKeywordValue}} are basically the same thing, as are {{CSSParserNumber}} and {{CSSNumberValue}}. Is it worthwhile to transplant this hierarchy underneath the {{CSSStyleValue}} superclass, and reuse the ones that are reasonable?

Opening this here so we can discuss it.

**Comment by gregwhitworth** [comment]
I think we should, I would like as much overlap where it makes sense

**Comment by tabatkins** [comment]
Yup, I think all the "value" classes can just be the CSSStyleValue subclasses. No reason to reproduce numbers, strings, etc. Even hashes are necessary to have in CSSStyleValue (for a UI property or two, I think).  The only new types we need to introduce are the ones for blocks.

**Comment by tabatkins** [comment]
I've updated the spec to handle this.  It's gonna need Typed OM to define a few more types, but Typed OM has to define those anyway - in particular, it'll need Hashes.

Typed OM might be able to take over arbitrary functions, I'm not sure.
